trigger:
- main

pool:
  name: 'Default'

stages:
  - stage: Build
    displayName: 'Build stage'
    jobs:
      - job: Build
        displayName: 'Build job'
        steps:
          - task: UseNode@1
            inputs:
              version: '20.x'

          - script: |
              npm install
              npm test -- --watchAll=false
              npm run build
            displayName: 'Install dependencies, run tests, and build'

          - task: CopyFiles@2
            inputs:
              contents: 'build/**'
              targetFolder: '$(Build.ArtifactStagingDirectory)'
            displayName: 'Copy files'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'
            displayName: 'Publish build artifacts'

  - stage: Deploy
    displayName: 'Deploy stage'
    jobs:
      - job: Deploy
        displayName: 'Deploy job'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'drop'
              targetPath: '$(Pipeline.Workspace)/drop'
            displayName: 'Download Build Artifacts'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'weather-conn'
              appName: 'weatherinfo'
              package: '$(Pipeline.Workspace)/drop'
              appType: 'webApp'
            displayName: 'Deploy to Azure Web App'